name: Go Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set-up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Build
        run: go build -ldflags "-s -w" -o bin/hopia src/*.go